-- ============================================================
-- SQL Case Study 1 | Intellipaat x IIT Indore
-- Problem  : Sales & Profit Analytics (Database Administrator)
-- Tables   : fact (4200 rows), product (13 rows), location (156 rows)
-- Author   : Himanshu Dave
-- ============================================================


-- ============================================================
-- Q1. Number of distinct states in LocationTable
-- ============================================================

SELECT count(DISTINCT State) as No_Of_States
FROM location;


-- ============================================================
-- Q2. Number of products of Regular type
-- ============================================================

SELECT count(DISTINCT Product) AS no_of_regular_products
FROM product
WHERE Type = 'Regular';


-- ============================================================
-- Q3. Total marketing spend on Product ID 1
-- ============================================================

SELECT sum(Marketing) as Total_Marketing_Spend
FROM fact
WHERE ProductId = 1;


-- ============================================================
-- Q4. Minimum sales per product (with product name)
-- ============================================================

SELECT
    f.ProductId,
    p.Product,
    min(f.Sales) AS Min_Sales
FROM fact f
LEFT JOIN product p ON f.ProductId = p.ProductId
GROUP BY f.ProductId, p.Product;


-- ============================================================
-- Q5. Maximum Cost of Goods Sold (COGS)
-- ============================================================

SELECT max(COGS) AS Max_COGS
FROM fact;


-- ============================================================
-- Q6. Product details where ProductType is 'Coffee'
-- ============================================================

SELECT *
FROM product
WHERE ProductType = 'Coffee';


-- ============================================================
-- Q7. Fact rows where TotalExpenses > 40
-- ============================================================

SELECT *
from fact
WHERE TotalExpenses > 40;


-- ============================================================
-- Q8. Average sales in area code 719
-- ============================================================

SELECT avg(Sales) as Avg_Sales
FROM fact
WHERE AreaCode = 719;


-- ============================================================
-- Q9. Total ACTUAL profit generated by Colorado state
--     NOTE: using Profit (actual), not BudgetProfit (forecast)
--           joining to location to avoid hardcoding area codes
-- ============================================================

SELECT sum(f.Profit) AS Total_Profit_Colorado
FROM fact f
JOIN location l ON l.AreaCode = f.AreaCode
WHERE l.State = 'Colorado';


-- ============================================================
-- Q10. Average inventory for each Product ID
-- ============================================================

SELECT
    ProductId,
    avg(Inventory) as Avg_Inventory
FROM fact
GROUP BY ProductId
ORDER BY ProductId;


-- ============================================================
-- Q11. States in sequential (alphabetical) order
-- ============================================================

SELECT DISTINCT State
FROM location
ORDER BY State;


-- ============================================================
-- Q12. Average budget metrics per product where AVG BudgetMargin > 100
--      NOTE: filter on aggregated value belongs in HAVING, not WHERE
-- ============================================================

SELECT
    ProductId,
    avg(BudgetProfit) as Avg_BudgetProfit,
    avg(BudgetCOGS)   AS Avg_BudgetCOGS,
    avg(BudgetMargin) as Avg_BudgetMargin,
    avg(BudgetSales)  AS Avg_BudgetSales
FROM fact
GROUP BY ProductId
HAVING avg(BudgetMargin) > 100
ORDER BY ProductId;


-- ============================================================
-- Q13. Total sales on 2010-01-01
-- ============================================================

SELECT sum(Sales) AS total_sales
FROM fact
WHERE Date = '2010-01-01';


-- ============================================================
-- Q14. Average total expense per Product ID per individual date
-- ============================================================

SELECT
    ProductId,
    Date,
    avg(TotalExpenses) as Avg_TotalExpenses
FROM fact
GROUP BY ProductId, Date
ORDER BY ProductId, Date;


-- ============================================================
-- Q15. Joined table: date, productID, product_type, product,
--      sales, profit, state, area_code
-- ============================================================

SELECT
    f.Date,
    f.ProductId,
    p.ProductType,
    p.Product,
    f.Sales,
    f.Profit,
    l.State,
    f.AreaCode
FROM fact f
JOIN product  p ON p.ProductId = f.ProductId
JOIN location l ON l.AreaCode  = f.AreaCode
ORDER BY f.ProductId;


-- ============================================================
-- Q16. Sales-wise rank with no gaps (DENSE_RANK)
-- ============================================================

SELECT *,
    dense_rank() OVER (ORDER BY Sales) as Sales_Rank
FROM fact;


-- ============================================================
-- Q17. State-wise profit and sales
-- ============================================================

SELECT
    l.State,
    sum(f.Sales)  as Total_Sales,
    sum(f.Profit) AS Total_Profit
FROM fact f
JOIN location l ON l.AreaCode = f.AreaCode
GROUP BY l.State;


-- ============================================================
-- Q18. State-wise profit and sales along with product name
-- ============================================================

SELECT
    l.State,
    p.Product,
    sum(f.Sales)  AS Total_Sales,
    sum(f.Profit) as Total_Profit
FROM fact f
JOIN location l ON l.AreaCode  = f.AreaCode
JOIN product  p ON p.ProductId = f.ProductId
GROUP BY l.State, p.Product;


-- ============================================================
-- Q19. Increased sales with 5% uplift
-- ============================================================

SELECT *,
    Sales + (0.05 * Sales) as increased_sales
FROM fact;


-- ============================================================
-- Q20. Maximum profit with Product ID and ProductType
-- ============================================================

SELECT
    f.ProductId,
    p.ProductType,
    max(f.Profit) AS Max_Profit
FROM fact f
LEFT JOIN product p ON f.ProductId = p.ProductId
GROUP BY f.ProductId, p.ProductType
ORDER BY f.ProductId;


-- ============================================================
-- Q21. Stored Procedure – fetch products by type (parameterized)
-- ============================================================

CREATE PROCEDURE GetProductsByType
    @ProductType varchar(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ProductId, ProductType, Product, Type
    FROM dbo.Product
    WHERE ProductType = @ProductType;
END;

-- Execute example
EXEC GetProductsByType @ProductType = 'Coffee';


-- ============================================================
-- Q22. Profit or Loss flag based on TotalExpenses threshold
-- ============================================================

SELECT *,
    CASE
        WHEN TotalExpenses < 60 THEN 'Profit'
        ELSE 'Loss'
    END as Profit_Or_Loss
FROM fact;


-- ============================================================
-- Q23. Weekly sales total with ROLLUP (hierarchical order)
-- ============================================================

SELECT
    datepart(WEEK, Date) as Week_Number,
    ProductId,
    sum(Sales)           AS Total_Sales
FROM fact
GROUP BY rollup(datepart(WEEK, Date), ProductId)
ORDER BY datepart(WEEK, Date), ProductId;


-- ============================================================
-- Q24. UNION and INTERSECT on AreaCode across fact and location
-- ============================================================

-- UNION: all unique AreaCodes from both tables
SELECT AreaCode FROM fact
UNION
SELECT AreaCode FROM location;

-- INTERSECT: AreaCodes common to both tables
SELECT AreaCode FROM fact
INTERSECT
SELECT AreaCode FROM location;


-- ============================================================
-- Q25. User-defined Table-Valued Function – fetch by product type
-- ============================================================

CREATE FUNCTION dbo.fn_GetProductsByType
(
    @ProductType varchar(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT ProductId, ProductType, Product, Type
    FROM dbo.Product
    WHERE ProductType = @ProductType
);

-- Usage
SELECT * FROM dbo.fn_GetProductsByType('Coffee');


-- ============================================================
-- Q26. Update ProductType Coffee → Tea for ProductId=1, then ROLLBACK
--      NOTE: use a transaction so the change can be undone safely
-- ============================================================

BEGIN TRANSACTION;

    UPDATE Product
    SET ProductType = 'Tea'
    WHERE ProductId = 1;

    -- Verify the change
    SELECT * FROM Product WHERE ProductId = 1;

ROLLBACK TRANSACTION;
-- Confirm original value is restored
SELECT * FROM Product WHERE ProductId = 1;


-- ============================================================
-- Q27. Date, ProductID, Sales where TotalExpenses between 100 and 200
-- ============================================================

SELECT
    Date,
    ProductId,
    Sales
FROM fact
WHERE TotalExpenses BETWEEN 100 AND 200;


-- ============================================================
-- Q28. Delete records from Product table where Type = 'Regular'
-- ============================================================

DELETE FROM product
WHERE Type = 'Regular';


-- ============================================================
-- Q29. ASCII value of the 5th character in the Product column
-- ============================================================

SELECT
    Product,
    ascii(substring(Product, 5, 1)) as Fifth_Char_ASCII
FROM Product;
